CREATE OR REPLACE TABLE AOL_SCHEMA.AIRPORTS(
    IATA_CODE VARCHAR(3),
    NAME VARCHAR(100),
    CITY VARCHAR(100),
    "STATE" VARCHAR(2),
    COUNTRY VARCHAR(100),
    LATITUDE DECIMAL(9,6),
    LONGITUDE DECIMAL(9,6)
);

IMPORT INTO AOL_SCHEMA.AIRPORTS
FROM LOCAL CSV FILE 'data/airports/airports_processed.csv' SKIP = 1;
