IMPORT INTO AOL_SCHEMA.TIMEDIM("ID", "year", "month", "day", "hour", "minute")
FROM LOCAL CSV FILE '../data/new_times.csv';

CREATE OR REPLACE TABLE AOL_SCHEMA.FLIGHTS(
    CARRIER VARCHAR(2),
    FLIGHT_NUMBER VARCHAR(4),
    TAIL_NUMBER VARCHAR(8),
    ORIGIN VARCHAR(3),
    DESTINATION VARCHAR(3),
    DELAY DECIMAL(4),
    DELAY_CARRIER DECIMAL(4),
    DELAY_WEATHER DECIMAL(4),
    DELAY_NAS DECIMAL(4),
    DELAY_SECURITY DECIMAL(4),
    DELAY_LATE_AIRCRAFT DECIMAL(4),
    SCHEDULED_TIME_ID DECIMAL(18),
    ACTUAL_TIME_ID DECIMAL(18),
)

IMPORT INTO AOL_SCHEMA.FLIGHTS
FROM LOCAL CSV FILE '../data/flights.csv';
